/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Forcing.Order.Filter

/-!
# Dense order embeddings and generic transport

A *dense order embedding* of forcing notions is an order embedding whose range is forcing-dense
(coinitial) in the target. The structure is deliberately minimal: a single `dense_range` field on
top of `P ↪o Q`. Monotonicity and order reflection come from the embedding, and compatibility
reflection is a theorem — a common strengthening of `e p` and `e q` sits above some `e s` by
density, and `s ≤ p`, `s ≤ q` follow by order reflection — so neither is a redundant field.

Generic transport is direction-asymmetric, and this file states exactly what holds:

* **Forward** (`mapPFilter`): a filter `G` on `P` pushes forward to the filter *generated by*
  its image — `{q | ∃ p ∈ G, e p ≤ q}` — and meeting a pulled-back dense set
  (`pullDense`) transports to meeting the original (`meets_mapPFilter`,
  `genericFor_mapPFilter`).
* **Reverse** (`comapPFilter`): the literal preimage of a filter on `Q` need not be a filter —
  see the counterexample at the bottom of this file, where the preimage is empty. The correct
  hypothesis is *localization of the filter in the range*: every member of `H` has a
  strengthening in `H ∩ range e`. In the model-relative setting (M3+), localization follows
  from `M`-genericity only once the relevant localized dense sets are shown to belong to `M`;
  meeting the range itself is insufficient. Here the hypothesis must be assumed.

There is no unconditional preimage transport theorem, by design. With the hypothesis, `map` and
`comap` are mutually inverse (`mapPFilter_comapPFilter`, `comapPFilter_mapPFilter`).

## Main definitions

* `Forcing.DenseOrderEmbedding P Q`: an order embedding with forcing-dense range.
* `Forcing.DenseOrderEmbedding.pullDense`: the transported dense set
  `{p | ∃ q ∈ D', e p ≤ q}`.
* `Forcing.DenseOrderEmbedding.mapPFilter`: the filter on `Q` generated by the image of a
  filter on `P`.
* `Forcing.DenseOrderEmbedding.comapPFilter`: the preimage filter of a range-localized filter
  on `Q` — reverse transport as a construction, with `map`/`comap` round trips.
-/

namespace Forcing

variable {P Q : Type*} [Preorder P] [Preorder Q]

/-- A *dense order embedding* of forcing notions: an order embedding whose range is
forcing-dense (coinitial) in the target. Monotonicity, order reflection, and compatibility
reflection are theorems, not fields. -/
structure DenseOrderEmbedding (P Q : Type*) [Preorder P] [Preorder Q] extends P ↪o Q where
  /-- Every condition in the target has a strengthening in the range. -/
  dense_range : IsCoinitial (Set.range toRelEmbedding)

namespace DenseOrderEmbedding

/-- The underlying order embedding. -/
def toOrderEmbedding (e : DenseOrderEmbedding P Q) : P ↪o Q :=
  e.toRelEmbedding

instance : CoeFun (DenseOrderEmbedding P Q) fun _ ↦ P → Q :=
  ⟨fun e ↦ e.toOrderEmbedding⟩

variable (e : DenseOrderEmbedding P Q) {p p' : P} {q : Q} {D' : Set Q}

protected theorem monotone : Monotone e :=
  e.toOrderEmbedding.monotone

@[simp] theorem le_iff_le : e p ≤ e p' ↔ p ≤ p' :=
  e.toOrderEmbedding.le_iff_le

/-- Density of the range, in applied form. -/
theorem exists_apply_le (q : Q) : ∃ p, e p ≤ q := by
  obtain ⟨y, ⟨p, rfl⟩, hy⟩ := e.dense_range q
  exact ⟨p, hy⟩

theorem compatible_map (h : Compatible p p') : Compatible (e p) (e p') :=
  let ⟨r, h1, h2⟩ := h
  ⟨e r, e.monotone h1, e.monotone h2⟩

/-- Compatibility is reflected as well as preserved: density of the range puts some `e s` below
any common strengthening, and order reflection pulls `s` below both preimages. -/
@[simp] theorem compatible_map_iff : Compatible (e p) (e p') ↔ Compatible p p' := by
  refine ⟨fun ⟨s, hs1, hs2⟩ ↦ ?_, e.compatible_map⟩
  obtain ⟨x, hx⟩ := e.exists_apply_le s
  exact ⟨x, e.le_iff_le.1 (hx.trans hs1), e.le_iff_le.1 (hx.trans hs2)⟩

@[simp] theorem incompatible_map_iff : Incompatible (e p) (e p') ↔ Incompatible p p' :=
  not_congr e.compatible_map_iff

/-- The transported dense set: conditions in `P` whose image strengthens a member of `D'`. -/
def pullDense (D' : Set Q) : Set P :=
  {p | ∃ q ∈ D', e p ≤ q}

theorem isDense_pullDense (hD' : IsDense D') : IsDense (e.pullDense D') := by
  intro p
  obtain ⟨q', hq'D, hq'⟩ := hD' (e p)
  obtain ⟨x, hx⟩ := e.exists_apply_le q'
  exact ⟨x, ⟨q', hq'D, hx⟩, e.le_iff_le.1 (hx.trans hq')⟩

/-- The filter on `Q` *generated by* the image of a filter on `P`: the upward closure
`{q | ∃ p ∈ G, e p ≤ q}`. The literal image need not be upward closed, and the literal preimage
of a filter need not be a filter at all, so generation is the right forward transport. -/
def mapPFilter (G : Order.PFilter P) : Order.PFilter Q :=
  (Order.IsPFilter.of_def (F := {q | ∃ p ∈ G, e p ≤ q})
    (by
      obtain ⟨p, hp⟩ := G.nonempty
      exact ⟨e p, p, hp, le_rfl⟩)
    (by
      rintro q₁ ⟨p₁, hp₁, h₁⟩ q₂ ⟨p₂, hp₂, h₂⟩
      obtain ⟨r, hrG, hr₁, hr₂⟩ := exists_mem_le_le hp₁ hp₂
      exact ⟨e r, ⟨r, hrG, le_rfl⟩, (e.monotone hr₁).trans h₁, (e.monotone hr₂).trans h₂⟩)
    (fun hxy ⟨p, hp, hple⟩ ↦ ⟨p, hp, hple.trans hxy⟩)).toPFilter

@[simp] theorem mem_mapPFilter {G : Order.PFilter P} :
    q ∈ e.mapPFilter G ↔ ∃ p ∈ G, e p ≤ q :=
  .rfl

/-- Meeting transports along the embedding as an equivalence: the generated filter meets `D'`
iff the base filter meets the pulled-back dense set. -/
theorem meets_mapPFilter_iff {G : Order.PFilter P} :
    Meets (e.mapPFilter G) D' ↔ Meets G (e.pullDense D') := by
  constructor
  · rintro ⟨q', ⟨p, hpG, hpq'⟩, hq'D⟩
    exact ⟨p, hpG, q', hq'D, hpq'⟩
  · rintro ⟨p, hpG, q', hq'D, hpq'⟩
    exact ⟨q', ⟨p, hpG, hpq'⟩, hq'D⟩

/-- Forward transport of meeting: if `G` meets the pulled-back dense set, the generated filter
meets the original. -/
theorem meets_mapPFilter {G : Order.PFilter P} (h : Meets G (e.pullDense D')) :
    Meets (e.mapPFilter G) D' :=
  e.meets_mapPFilter_iff.2 h

/-- Genericity transports along the embedding as an equivalence: the generated filter is generic
for a family iff the base filter is generic for the pulled-back family. -/
theorem genericFor_mapPFilter_iff {G : Order.PFilter P} {𝒟' : Set (Set Q)} :
    GenericFor 𝒟' (e.mapPFilter G) ↔ GenericFor (e.pullDense '' 𝒟') G := by
  constructor
  · rintro h E ⟨D', hD', rfl⟩
    exact e.meets_mapPFilter_iff.1 (h D' hD')
  · intro h D' hD'
    exact e.meets_mapPFilter_iff.2 (h _ (Set.mem_image_of_mem _ hD'))

/-- Forward transport of genericity: generic for the pulled-back family, generated filter
generic for the original family. -/
theorem genericFor_mapPFilter {G : Order.PFilter P} {𝒟' : Set (Set Q)}
    (h : GenericFor (e.pullDense '' 𝒟') G) : GenericFor 𝒟' (e.mapPFilter G) :=
  e.genericFor_mapPFilter_iff.2 h

/-- Reverse transport, correctly qualified: the preimage of a filter `H` on `Q` is a filter
provided `H` is *localized in the range* — every member of `H` has a strengthening in
`H ∩ range e`. In the model-relative setting, localization follows from `M`-genericity only
once the relevant localized dense sets are shown to belong to `M` (meeting the range itself is
insufficient); here it must be assumed, and without it the preimage can even be empty (see the
counterexample below). -/
theorem isPFilter_preimage {H : Order.PFilter Q}
    (hloc : ∀ q ∈ H, ∃ p, e p ∈ H ∧ e p ≤ q) :
    Order.IsPFilter (⇑e ⁻¹' (H : Set Q)) := by
  refine Order.IsPFilter.of_def ?_ ?_ ?_
  · obtain ⟨q', hq'⟩ := H.nonempty
    obtain ⟨p, hpH, -⟩ := hloc q' hq'
    exact ⟨p, hpH⟩
  · rintro p₁ hp₁ p₂ hp₂
    obtain ⟨r, hrH, hr₁, hr₂⟩ := exists_mem_le_le hp₁ hp₂
    obtain ⟨s, hsH, hsr⟩ := hloc r hrH
    exact ⟨s, hsH, e.le_iff_le.1 (hsr.trans hr₁), e.le_iff_le.1 (hsr.trans hr₂)⟩
  · exact fun hxy hx ↦ Order.PFilter.mem_of_le (e.monotone hxy) hx

/-- The preimage filter of a range-localized filter: reverse transport as a construction. -/
def comapPFilter (H : Order.PFilter Q) (hloc : ∀ q ∈ H, ∃ p, e p ∈ H ∧ e p ≤ q) :
    Order.PFilter P :=
  (e.isPFilter_preimage hloc).toPFilter

@[simp] theorem mem_comapPFilter {H : Order.PFilter Q}
    {hloc : ∀ q ∈ H, ∃ p, e p ∈ H ∧ e p ≤ q} {p : P} :
    p ∈ e.comapPFilter H hloc ↔ e p ∈ H :=
  .rfl

/-- Pushing a range-localized filter down and back up recovers it. -/
theorem mapPFilter_comapPFilter (H : Order.PFilter Q)
    (hloc : ∀ q ∈ H, ∃ p, e p ∈ H ∧ e p ≤ q) :
    e.mapPFilter (e.comapPFilter H hloc) = H := by
  ext q'
  constructor
  · rintro ⟨p, hpH, hpq'⟩
    exact Order.PFilter.mem_of_le hpq' hpH
  · exact fun hq' ↦ hloc q' hq'

/-- Generated filters are automatically range-localized. -/
theorem localized_mapPFilter (G : Order.PFilter P) :
    ∀ q ∈ e.mapPFilter G, ∃ p, e p ∈ e.mapPFilter G ∧ e p ≤ q :=
  fun _ ⟨p, hpG, hpq⟩ ↦ ⟨p, ⟨p, hpG, le_rfl⟩, hpq⟩

/-- Pulling a generated filter back recovers the base filter. -/
theorem comapPFilter_mapPFilter (G : Order.PFilter P) :
    e.comapPFilter (e.mapPFilter G) (e.localized_mapPFilter G) = G := by
  ext p
  constructor
  · rintro ⟨p', hp'G, hp'p⟩
    exact Order.PFilter.mem_of_le (e.le_iff_le.1 hp'p) hp'G
  · exact fun hp ↦ ⟨p, hp, le_rfl⟩

end DenseOrderEmbedding

/-!
### Why there is no unconditional preimage transport

The inclusion of the negative integers into `ℤ` is a dense order embedding (every integer has a
negative strengthening), yet the preimage of the principal filter at `5` is empty — not a
filter. Reverse transport genuinely needs the localization hypothesis of
`DenseOrderEmbedding.comapPFilter`.
-/

/-- The inclusion of the negative integers into `ℤ`, as a dense order embedding. -/
def negIntEmbedding : DenseOrderEmbedding {n : ℤ // n < 0} ℤ where
  toRelEmbedding := OrderEmbedding.subtype _
  dense_range := fun q ↦
    ⟨min q (-1), ⟨⟨min q (-1), lt_of_le_of_lt (min_le_right q (-1)) (by omega)⟩, rfl⟩,
      min_le_left q (-1)⟩

example : ⇑negIntEmbedding ⁻¹' (Order.PFilter.principal (5 : ℤ) : Set ℤ) = ∅ := by
  ext x
  simp only [Set.mem_preimage, Set.mem_empty_iff_false, iff_false]
  intro hx
  have h5 : (5 : ℤ) ≤ negIntEmbedding x := Order.PFilter.mem_principal.1 hx
  have hneg : (negIntEmbedding x : ℤ) < 0 := x.2
  omega

end Forcing
